print("wwww.", "kafamtersekoyum.", "com")
print(" ")
print("wwww.", "kafamtersekoyum.", "com", sep=(""))
print(" ")
print("ocak", "subat", "mart", "nisan", sep=("-"))
print(" ")
print("Kafmaters'e ", "Kenobi'ye ", "D^2'ye ", "Akmana'ya ", "Little-Soldier'a ", "Oresama'ya ", "Emolat'a ", "Enginar'a Koyam ", sep=("Koyam, "))
print(" ")
print(" ")
