print("wwww.", "kafamtersekoyum.", "com")
print(" ")
print("wwww.", "kafamtersekoyum.", "com", sep=(""))
print(" ")
print("ocak", "subat", "mart", "nisan", sep=("-"))
print(" ")
print("naber? ", "nasilsin? ", "ne yaparsin? ", sep=("iyidir "))
print(" ")
print(" ")
print("birinci satir", "ikinci satir", "12. satir", sep=("\n"))
print(" ")
print ("Efendim nasilsiniz? ", "Gununuz nasil gecti? ", sep=("\n"))
print(" ")
print("Bugun gunlerden sali ", end=("."))
print(" ")
print("Bugun gunlerden sali ", end=(".\n"))